<?php

namespace Database\Seeders;

use App\Models\Budget;
use Illuminate\Database\Seeder;

class BudgetSeeder extends Seeder
{
    public function run(): void
    {
        $budgets = [
            [
                'program_code' => 'GA',
                'activity_code' => '4645',
                'output_code' => 'CBE',
                'suboutput_code' => '001',
                'component_code' => '054',
                'subcomponent_code' => 'A',
                'account_code' => '537113',
                'item_code' => '00001',
                'coa' => 'GA.4645.CBE.001.054.A.537113.00001',
                'description' => 'Lanjutan Pengembangan Gedung Terminal Penumpang (Internasional)',
                'initial_budget' => 2400000000,
                'realized_budget' => 0,
                'remaining_budget' => 2400000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU, catatan per 171025',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4645',
                'output_code' => 'CBE',
                'suboutput_code' => '001',
                'component_code' => '054',
                'subcomponent_code' => 'A',
                'account_code' => '537113',
                'item_code' => '00002',
                'coa' => 'GA.4645.CBE.001.054.A.537113.00002',
                'description' => 'Pemenuhan Fasilitas dan Accessories Alur Keberangkatan dan Kedatangan',
                'initial_budget' => 900000000,
                'realized_budget' => 0,
                'remaining_budget' => 900000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU, catatan real sakti',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4645',
                'output_code' => 'CBE',
                'suboutput_code' => '001',
                'component_code' => '054',
                'subcomponent_code' => 'A',
                'account_code' => '537113',
                'item_code' => '00003',
                'coa' => 'GA.4645.CBE.001.054.A.537113.00003',
                'description' => 'Lanjutan Pembuatan Alur Bagasi Kedatangan',
                'initial_budget' => 100000000,
                'realized_budget' => 0,
                'remaining_budget' => 100000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU, catatan per 171025',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4646',
                'output_code' => 'CAD',
                'suboutput_code' => '001',
                'component_code' => '051',
                'subcomponent_code' => 'A',
                'account_code' => '537112',
                'item_code' => '00001',
                'coa' => 'GA.4646.CAD.001.051.A.537112.00001',
                'description' => 'Pengadaan dan Pemasangan CCTV Bandar Udara',
                'initial_budget' => 500000000,
                'realized_budget' => 0,
                'remaining_budget' => 500000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4646',
                'output_code' => 'CBE',
                'suboutput_code' => '001',
                'component_code' => '055',
                'subcomponent_code' => 'A',
                'account_code' => '537113',
                'item_code' => '00001',
                'coa' => 'GA.4646.CBE.001.055.A.537113.00001',
                'description' => 'Perluasan Halaman Parkir Kendaraan PKP-PK',
                'initial_budget' => 900000000,
                'realized_budget' => 0,
                'remaining_budget' => 900000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4646',
                'output_code' => 'CBE',
                'suboutput_code' => '002',
                'component_code' => '052',
                'subcomponent_code' => 'A',
                'account_code' => '525112',
                'item_code' => '00001',
                'coa' => 'GA.4646.CBE.002.052.A.525112.00001',
                'description' => 'Penyelenggaraan Latihan PKD (Full Scale) PKP-PK',
                'initial_budget' => 900000000,
                'realized_budget' => 0,
                'remaining_budget' => 900000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4646',
                'output_code' => 'CBE',
                'suboutput_code' => '002',
                'component_code' => '052',
                'subcomponent_code' => 'C',
                'account_code' => '525112',
                'item_code' => '00001',
                'coa' => 'GA.4646.CBE.002.052.C.525112.00001',
                'description' => 'Latihan Keadaan Darurat Keamanan Full Scale',
                'initial_budget' => 250000000,
                'realized_budget' => 0,
                'remaining_budget' => 250000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU',
                'year' => 2026,
            ],
            [
                'program_code' => 'GA',
                'activity_code' => '4646',
                'output_code' => 'CBE',
                'suboutput_code' => '002',
                'component_code' => '052',
                'subcomponent_code' => 'D',
                'account_code' => '525112',
                'item_code' => '00001',
                'coa' => 'GA.4646.CBE.002.052.D.525112.00001',
                'description' => 'Rapat Komite Keamanan',
                'initial_budget' => 225000000,
                'realized_budget' => 0,
                'remaining_budget' => 225000000,
                'status_pagu' => 'Aktif',
                'catatan' => 'Sumber: sheet Pagu_BLU',
                'year' => 2026,
            ],
        ];

        foreach ($budgets as $budget) {
            Budget::updateOrCreate(
                ['coa' => $budget['coa']],
                $budget
            );
        }
    }
}
