<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterCoa;

class MasterCoaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coas = [
            // === BELANJA PEGAWAI (51) ===
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '511111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.001.A.511111.001',
                'nama_akun'       => 'Belanja Gaji Pokok PNS',
                'jenis_akun'      => 'Belanja Pegawai',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '511119',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.001.A.511119.001',
                'nama_akun'       => 'Belanja Pembulatan Gaji PNS',
                'jenis_akun'      => 'Belanja Pegawai',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '511121',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.001.A.511121.001',
                'nama_akun'       => 'Belanja Tunjangan Suami/Istri PNS',
                'jenis_akun'      => 'Belanja Pegawai',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '511151',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.001.A.511151.001',
                'nama_akun'       => 'Belanja Tunjangan Kinerja',
                'jenis_akun'      => 'Belanja Pegawai',
            ],

            // === BELANJA BARANG (52) ===
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '521111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.A.521111.001',
                'nama_akun'       => 'Belanja Keperluan Perkantoran',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '521211',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.A.521211.001',
                'nama_akun'       => 'Belanja Bahan',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '522111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.A.522111.001',
                'nama_akun'       => 'Belanja Langganan Listrik',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '522112',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.A.522112.001',
                'nama_akun'       => 'Belanja Langganan Telepon',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '522113',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.A.522113.001',
                'nama_akun'       => 'Belanja Langganan Air',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '002',
                'kd_subkomponen'  => 'B',
                'kd_akun'         => '522151',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.002.B.522151.001',
                'nama_akun'       => 'Belanja Jasa Profesi',
                'jenis_akun'      => 'Belanja Barang',
            ],

            // === BELANJA JASA / HONOR (52) ===
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.QMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '521213',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.QMA.001.001.A.521213.001',
                'nama_akun'       => 'Belanja Honor Output Kegiatan',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.QMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '524111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.QMA.001.001.A.524111.001',
                'nama_akun'       => 'Belanja Perjalanan Dinas Biasa',
                'jenis_akun'      => 'Belanja Barang',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.QMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '001',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '524113',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.QMA.001.001.A.524113.001',
                'nama_akun'       => 'Belanja Perjalanan Dinas Dalam Kota',
                'jenis_akun'      => 'Belanja Barang',
            ],

            // === BELANJA MODAL (53) ===
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '003',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '531111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.003.A.531111.001',
                'nama_akun'       => 'Belanja Modal Tanah',
                'jenis_akun'      => 'Belanja Modal',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '003',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '532111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.003.A.532111.001',
                'nama_akun'       => 'Belanja Modal Peralatan dan Mesin',
                'jenis_akun'      => 'Belanja Modal',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '003',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '533111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.003.A.533111.001',
                'nama_akun'       => 'Belanja Modal Gedung dan Bangunan',
                'jenis_akun'      => 'Belanja Modal',
            ],

            // === BELANJA BARANG BLU (52) ===
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '004',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '525111',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.004.A.525111.001',
                'nama_akun'       => 'Belanja Barang BLU - Operasional',
                'jenis_akun'      => 'Belanja BLU',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '004',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '525112',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.004.A.525112.001',
                'nama_akun'       => 'Belanja Jasa BLU',
                'jenis_akun'      => 'Belanja BLU',
            ],
            [
                'kd_program'      => '054.01',
                'kd_giat'         => '2896',
                'kd_output'       => '2896.BMA',
                'kd_suboutput'    => '001',
                'kd_komponen'     => '004',
                'kd_subkomponen'  => 'A',
                'kd_akun'         => '525113',
                'kd_item'         => '001',
                'kode_mak_lengkap'=> '054.01.2896.BMA.001.004.A.525113.001',
                'nama_akun'       => 'Belanja Pemeliharaan BLU',
                'jenis_akun'      => 'Belanja BLU',
            ],
        ];

        foreach ($coas as $coa) {
            MasterCoa::updateOrCreate(
                ['kode_mak_lengkap' => $coa['kode_mak_lengkap']],
                $coa
            );
        }

        $this->command->info('✅ Master COA seeded: ' . count($coas) . ' records');
    }
}
