<?php

namespace Database\Seeders;

use App\Models\MasterPihak;
use App\Models\RekeningBank;
use Illuminate\Database\Seeder;

class MasterPihakSeeder extends Seeder
{
    public function run(): void
    {
        $pihaks = [
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-001',
                'npwp' => '01.234.567.8-901.000',
                'nama_pihak' => 'PT Maju Jaya Konstruksi',
                'nama_penanggung_jawab' => 'Andi Pratama',
                'tipe_supplier' => 'VENDOR',
                'alamat' => 'Jl. Ahmad Yani No. 10, Makassar',
                'email' => 'admin@majukonstruksi.co.id',
                'no_telepon' => '0411-555100',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Mandiri',
                    'nomor_rekening' => '1230001112223',
                    'nama_rekening' => 'PT Maju Jaya Konstruksi',
                    'kode_bank' => '008',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-002',
                'npwp' => '02.345.678.9-012.000',
                'nama_pihak' => 'CV Sinar Teknologi Nusantara',
                'nama_penanggung_jawab' => 'Rizal Hidayat',
                'tipe_supplier' => 'VENDOR',
                'alamat' => 'Jl. Perintis Kemerdekaan No. 25, Makassar',
                'email' => 'kontak@sinarteknologi.id',
                'no_telepon' => '0411-555200',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BNI',
                    'nomor_rekening' => '9876543210',
                    'nama_rekening' => 'CV Sinar Teknologi Nusantara',
                    'kode_bank' => '009',
                ],
            ],
            [
                'kategori' => 'PENERIMAAN',
                'jenis_entitas' => 'INSTANSI',
                'kode_pihak' => 'MTR-001',
                'npwp' => null,
                'nama_pihak' => 'Dinas Kesehatan Provinsi Sulawesi Selatan',
                'nama_penanggung_jawab' => 'Dr. H. Rahmat Saleh',
                'tipe_supplier' => 'MITRA',
                'alamat' => 'Jl. Jenderal Sudirman No. 88, Makassar',
                'email' => 'dinkes@sulselprov.go.id',
                'no_telepon' => '0411-555300',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Sulselbar',
                    'nomor_rekening' => '1002003004005',
                    'nama_rekening' => 'Dinas Kesehatan Prov. Sulsel',
                    'kode_bank' => '126',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-003',
                'npwp' => '03.456.789.0-123.000',
                'nama_pihak' => 'PT Cipta Sarana Medika',
                'nama_penanggung_jawab' => 'Dewi Lestari',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Boulevard Raya No. 12, Makassar',
                'email' => 'finance@ciptasaranamedika.co.id',
                'no_telepon' => '0411-555301',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Mandiri',
                    'nomor_rekening' => '1234500003001',
                    'nama_rekening' => 'PT Cipta Sarana Medika',
                    'kode_bank' => '008',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-004',
                'npwp' => '04.567.890.1-234.000',
                'nama_pihak' => 'CV Anugerah Alkes Sejahtera',
                'nama_penanggung_jawab' => 'Rahman Syamsuddin',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Hertasning Baru No. 45, Makassar',
                'email' => 'admin@anugerahalkes.id',
                'no_telepon' => '0411-555302',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BRI',
                    'nomor_rekening' => '66000300040055',
                    'nama_rekening' => 'CV Anugerah Alkes Sejahtera',
                    'kode_bank' => '002',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-005',
                'npwp' => '05.678.901.2-345.000',
                'nama_pihak' => 'PT Nusantara Digital Solusi',
                'nama_penanggung_jawab' => 'Fitrah Aditya',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. A.P. Pettarani No. 88, Makassar',
                'email' => 'billing@nusantaradigital.co.id',
                'no_telepon' => '0411-555303',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BNI',
                    'nomor_rekening' => '0090050006007',
                    'nama_rekening' => 'PT Nusantara Digital Solusi',
                    'kode_bank' => '009',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-006',
                'npwp' => '06.789.012.3-456.000',
                'nama_pihak' => 'CV Mitra Karya Utama',
                'nama_penanggung_jawab' => 'Nurul Azizah',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Veteran Selatan No. 19, Makassar',
                'email' => 'kontak@mitrakaryautama.id',
                'no_telepon' => '0411-555304',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Sulselbar',
                    'nomor_rekening' => '1260060007008',
                    'nama_rekening' => 'CV Mitra Karya Utama',
                    'kode_bank' => '126',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-007',
                'npwp' => '07.890.123.4-567.000',
                'nama_pihak' => 'PT Prima Energi Lestari',
                'nama_penanggung_jawab' => 'Ardiansyah Putra',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Pengayoman No. 31, Makassar',
                'email' => 'invoice@primaenergi.co.id',
                'no_telepon' => '0411-555305',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BCA',
                    'nomor_rekening' => '0140007008009',
                    'nama_rekening' => 'PT Prima Energi Lestari',
                    'kode_bank' => '014',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-008',
                'npwp' => '08.901.234.5-678.000',
                'nama_pihak' => 'CV Cahaya Mandiri Office',
                'nama_penanggung_jawab' => 'Sri Wahyuni',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Toddopuli Raya No. 52, Makassar',
                'email' => 'sales@cahayamandirioffice.id',
                'no_telepon' => '0411-555306',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Mandiri',
                    'nomor_rekening' => '1234500080090',
                    'nama_rekening' => 'CV Cahaya Mandiri Office',
                    'kode_bank' => '008',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-009',
                'npwp' => '09.012.345.6-789.000',
                'nama_pihak' => 'PT Bumi Sehat Farmasi',
                'nama_penanggung_jawab' => 'Hendra Wijaya',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Sultan Alauddin No. 101, Makassar',
                'email' => 'keuangan@bumisehatfarmasi.co.id',
                'no_telepon' => '0411-555307',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BNI',
                    'nomor_rekening' => '0090090010112',
                    'nama_rekening' => 'PT Bumi Sehat Farmasi',
                    'kode_bank' => '009',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-010',
                'npwp' => '10.123.456.7-890.000',
                'nama_pihak' => 'CV Global Teknik Perkasa',
                'nama_penanggung_jawab' => 'Baharuddin Malik',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Urip Sumoharjo No. 64, Makassar',
                'email' => 'office@globalteknikperkasa.id',
                'no_telepon' => '0411-555308',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BRI',
                    'nomor_rekening' => '66001000112233',
                    'nama_rekening' => 'CV Global Teknik Perkasa',
                    'kode_bank' => '002',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-011',
                'npwp' => '11.234.567.8-901.000',
                'nama_pihak' => 'PT Lentera Media Kreatif',
                'nama_penanggung_jawab' => 'Maya Kartika',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Landak Baru No. 7, Makassar',
                'email' => 'hello@lenteramedia.co.id',
                'no_telepon' => '0411-555309',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BCA',
                    'nomor_rekening' => '0140110012131',
                    'nama_rekening' => 'PT Lentera Media Kreatif',
                    'kode_bank' => '014',
                ],
            ],
            [
                'kategori' => 'PENGELUARAN',
                'jenis_entitas' => 'BADAN_USAHA',
                'kode_pihak' => 'VND-012',
                'npwp' => '12.345.678.9-012.000',
                'nama_pihak' => 'CV Sentosa Jaya Logistik',
                'nama_penanggung_jawab' => 'Taufik Akbar',
                'tipe_supplier' => '02 - Penyedia/Badan Usaha',
                'alamat' => 'Jl. Metro Tanjung Bunga No. 28, Makassar',
                'email' => 'ops@sentosalogistik.id',
                'no_telepon' => '0411-555310',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'Bank Sulselbar',
                    'nomor_rekening' => '1260120013141',
                    'nama_rekening' => 'CV Sentosa Jaya Logistik',
                    'kode_bank' => '126',
                ],
            ],
            [
                'kategori' => 'KEDUANYA',
                'jenis_entitas' => 'PERORANGAN',
                'kode_pihak' => 'PRG-001',
                'npwp' => '12.345.678.9-111.000',
                'nama_pihak' => 'Muhammad Fadli',
                'nama_penanggung_jawab' => 'Muhammad Fadli',
                'tipe_supplier' => 'PERSONAL',
                'alamat' => 'Jl. Emmy Saelan No. 7, Makassar',
                'email' => 'fadli@example.com',
                'no_telepon' => '081355500111',
                'status_aktif' => true,
                'rekening' => [
                    'nama_bank' => 'BRI',
                    'nomor_rekening' => '66001122334455',
                    'nama_rekening' => 'Muhammad Fadli',
                    'kode_bank' => '002',
                ],
            ],
        ];

        foreach ($pihaks as $item) {
            $rekening = $item['rekening'];
            unset($item['rekening']);

            $pihak = MasterPihak::updateOrCreate(
                ['kode_pihak' => $item['kode_pihak']],
                $item
            );

            RekeningBank::updateOrCreate(
                [
                    'pemilik_type' => MasterPihak::class,
                    'pemilik_id' => $pihak->id,
                    'nomor_rekening' => $rekening['nomor_rekening'],
                ],
                array_merge($rekening, [
                    'pemilik_type' => MasterPihak::class,
                    'pemilik_id' => $pihak->id,
                    'is_default' => true,
                    'status_aktif' => true,
                ])
            );
        }
    }
}
